apiVersion: com.pesco.operator/v1
kind: HadoopConfigFolder
metadata:
  name: ranger-config
  namespace: project-1
spec:
  config:
    - name: core-site
      namespace: bigdata
    - namespace: bigdata
      name: hdfs-site
